export const SET_BANNERS = 'SET_BANNERS';
export const SET_PERSONALIZED = 'SET_PERSONALIZED';
export const SET_NEW_ALBUMS = 'SET_NEW_ALBUMS';
export const SET_NEW_SONGS = 'SET_NEW_SONGS';
export const SET_DETAIL = 'SET_DETAIL';
export const SET_ALBUM_DATA = 'SET_ALBUM_DATA';
export const SET_FULL_SCREEN = 'SET_FULL_SCREEN';
export const SET_MINI_PLAYER = 'SET_MINI_PLAYER';
